
version: '3.7'

services:
  psql:
    image: postgres@sha256:61d5d8ef6cb4e2035f053f26b6b455c201a809354084cc8426b6904b8dd35602
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
  
  archiver-psql:
    image: docker-registry.siecobywatelska.plremote-archiver
    build:
      context: .
    environment:
      BACKUP_SRC: "postgresql"
      BACKUP_POSTGRESQL_HOST: db
      BACKUP_POSTGRESQL_HOST: psql
      BACKUP_POSTGRESQL_DATABASE: db
      BACKUP_POSTGRESQL_USER: root
      BACKUP_POSTGRESQL_PASSWORD: pass
    depends_on:
      - psql

  mysql:
    image: mysql@sha256:04ee7141256e83797ea4a84a4d31b1f1bc10111c8d1bc1879d52729ccd19e20a
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: pass

  archiver-mysql:
    build:
      context: .
    environment:
      BACKUP_SRC: "mysql"
      BACKUP_MYSQL_HOST: mysql
      BACKUP_MYSQL_DATABASE: db
      BACKUP_MYSQL_USER: root
      BACKUP_MYSQL_PASSWORD: example
    depends_on:
      - mysql
