
version: '3.7'

services:
  psql:
    image: postgres@sha256:9b52549a9a3c60d67719d57473017dd96adefea57fa8b2a39dba2cc4062b35a9
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
  
  archiver-psql:
    image: docker-registry.siecobywatelska.plremote-archiver
    build:
      context: .
    environment:
      BACKUP_SRC: "postgresql"
      BACKUP_POSTGRESQL_HOST: db
      BACKUP_POSTGRESQL_HOST: psql
      BACKUP_POSTGRESQL_DATABASE: db
      BACKUP_POSTGRESQL_USER: root
      BACKUP_POSTGRESQL_PASSWORD: pass
    depends_on:
      - psql

  mysql:
    image: mysql@sha256:c7788fdc4c04a64bf02de3541656669b05884146cb3995aa64fa4111932bec0f
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: pass

  archiver-mysql:
    build:
      context: .
    environment:
      BACKUP_SRC: "mysql"
      BACKUP_MYSQL_HOST: mysql
      BACKUP_MYSQL_DATABASE: db
      BACKUP_MYSQL_USER: root
      BACKUP_MYSQL_PASSWORD: example
    depends_on:
      - mysql
