version: '3'

services:
  monitoring:
    image: docker-registry.siecobywatelska.pl/zabbix-agent:latest@sha256:513f194af53257c2fdf2666bcf54ba4bd5ee941a451fdbf8e637c83ab55cef98
    ports:
      - "10050:10050"
    privileged: true
    environment:
      ZBX_HOSTNAME: "vm-agent-registry"
      ZBX_SERVER_HOST: "zabbix.127.0.0.1.xip.io"
      ZBX_SERVER_PORT: "10050"
    restart: always

