version: '3'

services:
  monitoring:
    image: docker-registry.siecobywatelska.pl/zabbix-agent:latest@sha256:5f55bc1ff78fffc4ff33dc9edf7b6e3cc9da1f805aa57ddde7e0b8b401b70ef4
    ports:
      - "10050:10050"
    privileged: true
    environment:
      ZBX_HOSTNAME: "vm-agent-registry"
      ZBX_SERVER_HOST: "zabbix.127.0.0.1.xip.io"
      ZBX_SERVER_PORT: "10050"
    restart: always

