version: '3'

services:
  monitoring:
    image: docker-registry.siecobywatelska.pl/zabbix-agent:latest@sha256:0218230d4cc81f712ae609dbf82fc81f62fd1ea3b34ae8b6289ce32e1cc4da6b
    ports:
      - "10050:10050"
    privileged: true
    environment:
      ZBX_HOSTNAME: "vm-agent-registry"
      ZBX_SERVER_HOST: "zabbix.127.0.0.1.xip.io"
      ZBX_SERVER_PORT: "10050"
    restart: always

