version: '3'

services:
  monitoring:
    image: docker-registry.siecobywatelska.pl/zabbix-agent:latest@sha256:35e2bdc787615df4f20566ca75f39d87b95d57b5cb8a10c81362c5edac144919
    ports:
      - "10050:10050"
    privileged: true
    environment:
      ZBX_HOSTNAME: "vm-agent-registry"
      ZBX_SERVER_HOST: "zabbix.127.0.0.1.xip.io"
      ZBX_SERVER_PORT: "10050"
    restart: always

