version: '3'

services:
  monitoring:
    image: docker-registry.siecobywatelska.pl/zabbix-agent:latest@sha256:a9b7ce5ec76d38cca932a6c25a3db83162fae2af107777e9684fae213aa4750b
    ports:
      - "10050:10050"
    privileged: true
    environment:
      ZBX_HOSTNAME: "vm-agent-registry"
      ZBX_SERVER_HOST: "zabbix.127.0.0.1.xip.io"
      ZBX_SERVER_PORT: "10050"
    restart: always

